services:
  - type: web
    name: farmlink
    runtime: java
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/farmlink-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: JAVA_VERSION
        value: 17
