server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/farmlink_db
spring.datasource.username=postgres
spring.datasource.password=Soham@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=true

app.jwt.secret=FarmLinkSuperSecretKey2024ChangeThisToSomethingLongerForSecurity123456
app.jwt.expiration=86400000

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration